### ISSUE TITLE
cannot open the .exe, immediately closes

### ISSUE THREAD

**Issue by braaaains** [MikePia/structjour#7]
I can't really figure out where I'm going wrong on this install. The program won't run.

when I double click the structjour.exe in my Scripts folder, a cmd window pops up for a fraction of a second, then closes. I was able to screenshot it: [https://i.imgur.com/Qu5htmS.png](url), basically files has loaded then ends with ModuleNotFoundError: no module named 'sqlalchemy'

i thought maybe I could install that via pip to resolve the error. It didn't solve the problem, but it changed the error message to [https://i.imgur.com/F6vNP14.png](url) ModuleNotFoundError: no module named 'structjour.view.forms'

I program looks great, and I'd love to try it. Just can't seem to figure this out on my own.

**Comment by jjsadek** [comment]
Same issue here. Here is the output log.

`Traceback (most recent call last):
  File "C:\Users\jadsa\AppData\Local\Programs\Python\Python38\Scripts\structjour-script.py", line 11, in <module>
    load_entry_point('structjour==0.9.93a6', 'console_scripts', 'structjour')()
  File "c:\users\jadsa\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\jadsa\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "c:\users\jadsa\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2462, in load
    return self.resolve()
  File "c:\users\jadsa\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\jadsa\appdata\local\programs\python\python38\lib\site-packages\structjour\view\runtrade.py", line 45, in <module>
    from structjour.migrations.check_migration import checkMigration
  File "c:\users\jadsa\appdata\local\programs\python\python38\lib\site-packages\structjour\migrations\check_migration.py", line 28, in <module>
    import structjour.migrations._0003_model_trade_sum_dataonly as migrate0003
  File "c:\users\jadsa\appdata\local\programs\python\python38\lib\site-packages\structjour\migrations\_0003_model_trade_sum_dataonly.py", line 77, in <module>
    class Migration:
  File "c:\users\jadsa\appdata\local\programs\python\python38\lib\site-packages\structjour\migrations\_0003_model_trade_sum_dataonly.py", line 85, in Migration
    ModelBase.createAll(),
  File "c:\users\jadsa\appdata\local\programs\python\python38\lib\site-packages\structjour\models\meta.py", line 109, in createAll
    raise ValueError('ModelBase.connect() must be called prior to createAll()')
ValueError: ModelBase.connect() must be called prior to createAll()`

**Comment by MikePia** [comment]
Braaaains, 
Thank you for reporting this issue. Sorry for my absence. 
This was some months ago. Have you tried it since? The error looks like the sqlalchemy import was not included in your build.  That was addressed in July 29 commit, just days after your post. If it is still a problem, I would very much like to know about it.
