### ISSUE TITLE
Errors after installation

### ISSUE THREAD

**Issue by BrusNoland** [MikePia/structjour#9]
No errors during installation. Windows 10 Enterprise.
Not running, here is traceback.
```
Traceback (most recent call last):
  File "d:\funsoft\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\funsoft\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\FunSoft\Python\Scripts\structjour.exe\__main__.py", line 4, in <module>
  File "d:\funsoft\python\lib\site-packages\structjour\view\runtrade.py", line 45, in <module>
    from structjour.migrations.check_migration import checkMigration
  File "d:\funsoft\python\lib\site-packages\structjour\migrations\check_migration.py", line 28, in <module>
    import structjour.migrations._0003_model_trade_sum_dataonly as migrate0003
  File "d:\funsoft\python\lib\site-packages\structjour\migrations\_0003_model_trade_sum_dataonly.py", line 77, in <module>
    class Migration:
  File "d:\funsoft\python\lib\site-packages\structjour\migrations\_0003_model_trade_sum_dataonly.py", line 85, in Migration
    ModelBase.createAll(),
  File "d:\funsoft\python\lib\site-packages\structjour\models\meta.py", line 109, in createAll
    raise ValueError('ModelBase.connect() must be called prior to createAll()')
ValueError: ModelBase.connect() must be called prior to createAll()
```
Thank you!

**Comment by MikePia** [comment]
Thank you, I'll try to get to this next week. I have seen errors like this caused by migrating to SQLAlchemy for db access. 

Does this happen when you first run it before any window comes up?

**Comment by BrusNoland** [comment]
Mike thank you for your time!
Yeah, it happens before a window comes up.
First launch I did by clicking on "structjour.exe" - for a moment I saw a cmd window with the errors.
Then I tried the same thing a few times starting it through cmd, and it always the same traceback.

Not sure if it's helpful, but here are all modules installed on my system:

```
>>> help("modules")

Please wait a moment while I gather a list of all available modules...

D:\FunSoft\Python\lib\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
D:\FunSoft\Python\lib\site-packages\~ip\_vendor\requests\__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
PIL                 bdb                 ftplib              reprlib
PyQt5               binascii            functools           requests
__future__          binhex              gc                  requests_oauthlib
_abc                bisect              genericpath         rfc3986
_ast                brain_argparse      getopt              rlcompleter
_asyncio            brain_attrs         getpass             runpy
_bisect             brain_boto3         gettext             sched
_blake2             brain_builtin_inference glob                scipy
_bootlocale         brain_collections   gzip                seaborn
_bz2                brain_crypt         h11                 secrets
_cffi_backend       brain_curses        hashlib             select
_codecs             brain_dataclasses   heapq               selectors
_codecs_cn          brain_dateutil      hmac                selenium
_codecs_hk          brain_fstrings      html                setuptools
_codecs_iso2022     brain_functools     http                shelve
_codecs_jp          brain_gi            httpcore            shlex
_codecs_kr          brain_hashlib       httpx               shutil
_codecs_tw          brain_http          idlelib             signal
_collections        brain_io            idna                site
_collections_abc    brain_mechanize     imaplib             six
_compat_pickle      brain_multiprocessing imghdr              smtpd
_compression        brain_namedtuple_enum imp                 smtplib
_contextvars        brain_nose          importlib           sndhdr
_csv                brain_numpy_core_fromnumeric inspect             sniffio
_ctypes             brain_numpy_core_function_base io                  socket
_ctypes_test        brain_numpy_core_multiarray ipaddress           socketserver
_datetime           brain_numpy_core_numeric isort               soupsieve
_decimal            brain_numpy_core_numerictypes itertools           sqlalchemy
_dummy_thread       brain_numpy_core_umath jdcal               sqlite3
_elementtree        brain_numpy_ndarray json                sre_compile
_functools          brain_numpy_random_mtrand keyword             sre_constants
_hashlib            brain_numpy_utils   kiwisolver          sre_parse
_heapq              brain_pkg_resources lazy_object_proxy   ssl
_imp                brain_pytest        lib2to3             stat
_io                 brain_qt            linecache           statistics
_json               brain_random        locale              string
_locale             brain_re            logging             stringprep
_lsprof             brain_responses     lxml                struct
_lzma               brain_scipy_signal  lzma                structjour
_markupbase         brain_six           mailbox             subprocess
_md5                brain_ssl           mailcap             sunau
_msi                brain_subprocess    marshal             symbol
_multibytecodec     brain_threading     math                symtable
_multiprocessing    brain_typing        matplotlib          sys
_opcode             brain_uuid          mccabe              sysconfig
_operator           bs4                 mimetypes           tabnanny
_osx_support        builtins            mmap                tabulate
_overlapped         bz2                 modulefinder        tarfile
_pickle             cProfile            mpl_finance         tda
_py_abc             calendar            mplfinance          telnetlib
_pydecimal          certifi             msilib              tempfile
_pyio               cffi                msvcrt              termcolor
_queue              cgi                 multiprocessing     test
_random             cgitb               multitasking        tests
_sha1               chardet             netrc               textwrap
_sha256             chromedriver        nntplib             this
_sha3               chunk               nt                  threading
_sha512             cmath               ntpath              time
_signal             cmd                 nturl2path          timeit
_sitebuiltins       code                numbers             tkinter
_socket             codecs              numpy               token
_sqlite3            codeop              oauthlib            tokenize
_sre                collections         opcode              toml
_ssl                colorama            openpyxl            trace
_stat               colorsys            operator            traceback
_statistics         compileall          optparse            tracemalloc
_string             concurrent          os                  tty
_strptime           configparser        pandas              turtle
_struct             contextlib          pandas_datareader   turtledemo
_symtable           contextvars         parser              types
_testbuffer         copy                pathlib             typing
_testcapi           copyreg             pdb                 unicodedata
_testconsole        crayons             pickle              unittest
_testimportmultiple crypt               pickletools         urllib
_testmultiphase     cryptography        pip                 urllib3
_thread             csv                 pipes               uu
_threading_local    ctypes              pkg_resources       uuid
_tkinter            curses              pkgutil             venv
_tracemalloc        cycler              platform            warnings
_warnings           dataclasses         plistlib            wave
_weakref            datetime            poplib              wcwidth
_weakrefset         dateutil            posixpath           weakref
_winapi             dbm                 pprint              webbrowser
_xxsubinterpreters  decimal             prettytable         webdriver_manager
abc                 difflib             profile             websockets
aifc                dis                 pstats              wheel
aiostream           distutils           pty                 winreg
antigravity         doctest             py_compile          winsound
argparse            dummy_threading     pyclbr              wrapt
array               easy_install        pycodestyle         wsgiref
ast                 email               pycparser           xdrlib
astroid             encodings           pydoc               xlrd
asynchat            ensurepip           pydoc_data          xml
asyncio             enum                pyexpat             xmlrpc
asyncore            errno               pylab               xxsubtype
atexit              et_xmlfile          pylint              yfinance
audioop             faulthandler        pyparsing           zipapp
authlib             filecmp             pytz                zipfile
autopep8            fileinput           queue               zipimport
backports           fnmatch             quopri              zlib
backtrader          formatter           random              ~ip
base64              fractions           re
```
Thank you again!

**Comment by MikePia** [comment]
I found the same errors you did and did some fixes. 

I updated this a while ago (both here and on Pypi 0.9.95a1), but I have not found the time to do any testing on it so I didn't report it here. 

It looks like it will be a little while till I can do proper testing, but, in famous last words, it worked on my system. :)

**Comment by BrusNoland** [comment]
Yay!!!!
Mike, thank you so much, it works on my system too! I'm excited to use this great tool!
P.S. I will report issues if they found.
